name: Deploy to Beta (TestFlight & Internal Testing)

on:
  push:
    tags:
      - 'v*-beta*'  # Ex: v1.0.0-beta1

jobs:
  build-beta:
    name: Build & Submit Beta
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🏷️ Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔧 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📱 Build iOS for TestFlight
        id: ios-build
        run: |
          eas build --platform ios --profile beta --non-interactive --no-wait
          echo "Build submitted to EAS"

      - name: 🤖 Build Android for Internal Testing
        id: android-build
        run: |
          eas build --platform android --profile beta --non-interactive --no-wait
          echo "Build submitted to EAS"

      - name: 📝 Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Beta ${{ steps.version.outputs.VERSION }}
          body: |
            ## 🧪 Beta Release ${{ steps.version.outputs.VERSION }}

            ### iOS (TestFlight)
            Build submitted to TestFlight. Beta testers will receive notification within 1 hour.

            ### Android (Internal Testing)
            Build will be available in Google Play Console → Internal Testing

            ### Testing Instructions
            1. Install from TestFlight (iOS) or Internal Testing link (Android)
            2. Test all features, especially chat functionality
            3. Report bugs via GitHub Issues with label `beta-feedback`

            ### Changes in this release
            See commit history for detailed changes.
          draft: false
          prerelease: true

      - name: 💬 Notify Slack
        if: always() && secrets.SLACK_WEBHOOK != ''
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "🧪 Beta build ${{ steps.version.outputs.VERSION }} submitted!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Beta Release*: ${{ steps.version.outputs.VERSION }}\n*Status*: ${{ job.status }}\n*Platform*: iOS + Android"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
