name: Deploy to Production (App Store & Google Play)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Ex: v1.0.0 (sem -beta)

jobs:
  build-production:
    name: Build & Submit Production
    runs-on: ubuntu-latest
    timeout-minutes: 90
    environment: production  # GitHub environment with approvals

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🏷️ Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Deploying version: $VERSION"

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: ✅ Run production checks
        run: |
          echo "Running pre-deploy checks..."
          npm run lint
          npx tsc --noEmit
          echo "All checks passed!"

      - name: 🔧 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📱 Build iOS for App Store
        id: ios-build
        run: |
          echo "Building iOS production..."
          eas build --platform ios --profile production --non-interactive
          echo "iOS build completed"

      - name: 🍎 Submit to App Store
        run: |
          echo "Submitting to App Store..."
          eas submit --platform ios --latest --profile production
          echo "Submitted to App Store for review"

      - name: 🤖 Build Android for Google Play
        id: android-build
        run: |
          echo "Building Android production..."
          eas build --platform android --profile production --non-interactive
          echo "Android build completed"

      - name: 🔑 Setup Google Play credentials
        run: |
          echo "${{ secrets.GOOGLE_PLAY_KEY_JSON }}" | base64 -d > google-play-key.json
          echo "Google Play credentials configured"

      - name: 🤖 Submit to Google Play
        run: |
          echo "Submitting to Google Play..."
          eas submit --platform android --latest --track production
          echo "Submitted to Google Play for review"

      - name: 📝 Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## 🚀 Production Release ${{ steps.version.outputs.VERSION }}

            ### App Store (iOS)
            ✅ Submitted for review
            - Expected review time: 24-48 hours
            - Will be available automatically after approval

            ### Google Play (Android)
            ✅ Submitted for review
            - Expected review time: 1-7 days
            - Staged rollout: 20% → 50% → 100%

            ### What's New
            [Add release notes here - what's new in this version]

            ### Breaking Changes
            [List any breaking changes if applicable]

            ### Bug Fixes
            [List bug fixes in this release]

            ---

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.version.outputs.VERSION }}...main
          draft: false
          prerelease: false

      - name: 💬 Notify Team
        if: always()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "🚀 Production Deploy ${{ steps.version.outputs.VERSION }}!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚀 Production Deployment"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Version:*\n${{ steps.version.outputs.VERSION }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\n${{ job.status }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*iOS:*\nSubmitted to App Store"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Android:*\nSubmitted to Google Play"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Review typically takes 24-48h for iOS and 1-7 days for Android."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: 📊 Update monitoring
        if: success()
        run: |
          echo "Deployment successful - updating monitoring dashboards"
          # Add Sentry release
          # Add DataDog deployment marker
          # etc.
